3.3 다변수 연속값 상태를 이산변수로 변환하기

In [83]:
# 구현에 사용할 패키지 임포트
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import gymnasium as gym

In [84]:
# 상수 정의
ENV = 'CartPole-v1' # 태스크 이름
NUM_DIZITIZED = 6 # 각 상태를 이산변수로 변환할 구간 수

In [85]:
# CartPole 실행
env = gym.make(ENV) # 태스크 실행 환경 생성
observation = env.reset() # 환경 초기화

In [86]:
# 이산변수 변환에 사용할 구간을 계산


def bins(clip_min, clip_max, num):
    '''관측된 상태(연속값)을 이산값으로 변환하는 구간을 계산'''
    return np.linspace(clip_min, clip_max, num + 1)[1:-1]

In [87]:
np.linspace(-2.4, 2.4, 6 + 1)

array([-2.4, -1.6, -0.8,  0. ,  0.8,  1.6,  2.4])

In [88]:
np.linspace(-2.4, 2.4, 6 + 1)[1:-1]

array([-1.6, -0.8,  0. ,  0.8,  1.6])

In [89]:
def digitize_state(observation):
    '''관측된 상태(observation)을 이산값으로 변환'''
    cart_pos, cart_v, pole_angle, pole_v = observation[0]
    digitized = [
        np.digitize(cart_pos, bins=bins(-2.4, 2.4, NUM_DIZITIZED)),
        np.digitize(cart_v, bins=bins(-3.0, 3.0, NUM_DIZITIZED)),
        np.digitize(pole_angle, bins=bins(-0.5, 0.5, NUM_DIZITIZED)),
        np.digitize(pole_v, bins=bins(-2.0, 2.0, NUM_DIZITIZED))]
    return sum([x * (NUM_DIZITIZED**i) for i, x in enumerate(digitized)])

In [90]:
digitize_state(observation)

<class 'tuple'>
(array([ 0.02486578, -0.0041425 , -0.00821451, -0.0313946 ], dtype=float32), {})


519